env:
  global:
    - NODE_ENV=test
  
language: node_js
node_js:
  - '10.15.1'
cache:
  directories:
    - node_modules
branches:
  only:
    - develop
install:
  - npm install

script:
  - npm run test:ci
after_success:
  - npm run coveralls
